version: '3'
services:
  gerrit1:
    build: gerrit/.
    ports:
      - "8080:8080"
      - "29418:29418"
      - "5005:5005"
    networks:
      - app

  gerrit2:
    build: gerrit/.
    ports:
      - "8081:8080"
      - "29419:29418"
      - "5006:5006"
    depends_on:
      - gerrit1
    networks:
      - app

networks:
  app:
    name: app
