version: '3'
services:
  gerrit1:
    build: gerrit/.
    ports:
      - "18080:8080"
      - "29418:29418"
      - "5005:5005"
    environment:
      - DEBUG_PORT=5005
      - PEER_INSTANCE=gerrit2      
    volumes:
      - git_data:/var/gerrit/git:rw
      - websessions_data:/var/gerrit/websessions:rw
      - logs-gerrit1:/var/gerrit/logs:rw
    networks:
      - app

  gerrit2:
    build: gerrit/.
    ports:
      - "18081:8080"
      - "29419:29418"
      - "5006:5006"
    environment:
      - DEBUG_PORT=5005
      - PEER_INSTANCE=gerrit1
    volumes:
      - git_data:/var/gerrit/git:rw
      - websessions_data:/var/gerrit/websessions:rw
      - logs-gerrit2:/var/gerrit/logs:rw
    depends_on:
      - gerrit1
    networks:
      - app

  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    ports:
      - "8080:80"
      - "8404:8404"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro
    depends_on:
      - gerrit1
      - gerrit2
    networks:
      - app

networks:
  app:
    name: app


volumes:
  git_data:
  websessions_data:
  logs-gerrit1:
  logs-gerrit2: